# .streamlit/secrets.toml
OPENAI_API_KEY = "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"

dark_theme = """
<style>
body {
    background-color: #121212;  /* Cor de fundo */
    color: white;               /* Cor do texto */
    font-family: Arial, sans-serif;
}
.st-bw {
    background-color: #1E1E1E;  /* Cor de fundo das caixas de chat */
    border-radius: 10px;
    padding: 10px;
    margin: 10px 0;
}
</style>
"""
